import React, { useMemo, useState } from 'react';
import { percentage } from '../engine/ScoringEngine';
import CaseVisual from './CaseVisual';
import './final-case.css';

const meta={TinniSense:{tone:'tinnitus',label:'TINNISENSE'},RehabMind:{tone:'rehab',label:'REHABMIND'},HearWise:{tone:'hearing',label:'HEARWISE'}};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));

function makeScenario(c){
 if(c.simulation) return {...c.simulation,module:c.module,patientData:c.patient,caseTitle:c.title,audiogram:c.audiogram};
 const p=c.patient||{}; const f=c.keyFeatures||[]; const vals=f.map(x=>x.value).join(' • '); const id=c.id;
 const maps={
  A1:['I have noticed ringing in both ears for quite a while.','When is it most noticeable, and how does it affect your day or sleep?','It is mostly there in quiet situations. I also notice that conversations are harder than they used to be.'],
  A3:['There is a whooshing sound that seems to follow my heartbeat.','Is it synchronous with your pulse, and when did it start?','Yes, it follows my heartbeat. I am worried because it feels different from ordinary ringing.'],
  A4:['The tinnitus is keeping me awake and I am exhausted.','How is the tinnitus affecting sleep, distress and your daily functioning?','I am sleeping badly and feeling very anxious about it. I need help coping with this.'],
  A5:['I hear a high-pitched sound even though I was told my hearing test is normal.','How intrusive is it, and are there other ear or hearing concerns?','It is persistent and distracting. I was wondering whether I need hearing aids.'],
  A6:['Normal sounds can feel painfully loud, and the tinnitus makes it worse.','Which sounds trigger discomfort, and what do you currently do to avoid them?','Busy places are difficult. I have started wearing protection much of the time.'],
  B1:['I keep missing parts of conversations at family meals.','Which people, places and situations are most important for you to communicate in?','Mostly small family meals. I want fewer repetitions and to feel included.'],
  B2:['Meetings and lectures have become difficult because there is so much background noise.','What listening situations matter most and what would successful communication look like?','Boardrooms and lectures. I need to follow several speakers without constantly asking them to repeat.'],
  B3:['I struggle to understand my children on the phone, and handling my devices is difficult.','How do you use the phone and alerts, and what makes device handling difficult?','I live alone and need reliable calls and alerts. Small controls are hard for me to manage.'],
  B4:['My family thinks I need a hearing aid, but I am not ready for one.','What concerns you about hearing technology, and what would make you comfortable exploring options?','I do not want to be pushed into a device. I want to decide when I am ready.'],
  C1:['I need to hear people in restaurants and I use my smartphone constantly.','Which environments and phone functions are most important to you?','Restaurants are difficult, and I want reliable streaming without losing natural sound.'],
  C2:['Speech still sounds unclear even when high-frequency sounds seem loud enough.','Tell me about clarity, comfort and what happened with your current fitting.','More high-frequency amplification has not made speech clearer, and sometimes it is uncomfortable.'],
  C3:['I cannot see the tiny controls well, and my hands are not as steady as they used to be.','What parts of handling, charging or controlling the device are hardest?','Small buttons and indicators are difficult. I need something I can manage independently.'],
  C4:['My hearing aid whistles, and my own voice sounds strange.','When does the whistling happen, and how would you describe your own voice?','The whistle is worse when I move or touch the aid. My own voice sounds blocked and unnatural.']
 };
 const x=maps[id]||[p.chiefConcern||'I am having difficulty with my hearing.','Can you tell me more about what is difficult in daily life?','The main problem is affecting my everyday communication.'];
 return {initialTrust:55,initialEmotion:id==='B4'?'concerned':id==='A4'?'distressed':'calm',initialEngagement:62,module:c.module,patientData:p,caseTitle:c.title,audiogram:c.audiogram,patient:{name:`Simulated patient · ${id}`,avatar:p.sex?.[0]||'P',intro:`${p.age||''}-year-old ${p.sex||'patient'} · ${p.chiefConcern||c.title}`},turns:[
  {patient:x[0],prompt:'Begin the encounter. What is your first move?',options:[{id:'a',text:'Invite the patient to describe the problem in their own words before narrowing the assessment.',style:'Open-ended',trust:10,engagement:9,relevance:1,empathy:2,reveals:['Patient narrative obtained']},{id:'b',text:'Move straight to the test or device without exploring the experience.',style:'Test-first',trust:-7,engagement:-8,harm:1,emotion:'anxious'},{id:'c',text:'Reassure the patient immediately that everything will be fine.',style:'Premature reassurance',trust:-5,engagement:-6,harm:1}]},
  {patient:x[1],prompt:'What should you explore next?',options:[{id:'a',text:'Clarify timing, context, functional impact, associated concerns and the patient’s priorities.',style:'Targeted history',trust:9,engagement:8,relevance:2,empathy:1,reveals:['Context and functional impact']},{id:'b',text:'Focus only on the audiogram or technical specification.',style:'Data-only',trust:-3,engagement:-4},{id:'c',text:'Tell the patient that people with this profile usually have the same problem.',style:'Assumption',trust:-9,engagement:-9,harm:1,emotion:'concerned'}]},
  {patient:x[2],prompt:'The patient has given you a meaningful clue. How do you respond?',options:[{id:'a',text:'Reflect the concern, ask a focused follow-up question and explain why the information matters.',style:'Empathic clinical exploration',trust:11,engagement:10,relevance:2,empathy:3,emotion:'reassured',reveals:[vals||'Decision-driving patient information']},{id:'b',text:'Ignore the clue and continue with your planned questions.',style:'Missed information',trust:-5,engagement:-6},{id:'c',text:'Tell the patient not to worry until all testing is complete.',style:'Dismissive reassurance',trust:-10,engagement:-10,harm:1,emotion:'anxious'}]}
 ]};
}

export default function FinalCaseEngine({caseData,onBack,onComplete}){
 const m=meta[caseData.module]||meta.TinniSense; const sim=useMemo(()=>makeScenario(caseData),[caseData]);
 const [phase,setPhase]=useState('encounter'),[turn,setTurn]=useState(0),[trust,setTrust]=useState(sim.initialTrust||55),[engagement,setEngagement]=useState(sim.initialEngagement||60),[emotion,setEmotion]=useState(sim.initialEmotion||'calm'),[history,setHistory]=useState([]),[revealed,setRevealed]=useState([]),[answers,setAnswers]=useState({}),[stage,setStage]=useState(0),[follow,setFollow]=useState(null),[confidence,setConfidence]=useState(0);
 const stages=useMemo(()=>{const s=caseData.stages||[];const feature={id:'feature-extraction',title:'Extract decision-driving features',prompt:caseData.featurePrompt||'Which information should be carried forward?',options:[{id:'a',text:(caseData.keyFeatures||[]).slice(0,3).map(x=>`${x.label}: ${x.value}`).join(' · ')||'Patient goals, relevant clinical findings and safety considerations',score:0},{id:'b',text:'Only the audiogram or test result',score:0},{id:'c',text:'Only the patient’s preferred device',score:0}],scoreless:true};const out=[];s.forEach((x,i)=>{out.push(x);if(i===0)out.push(feature)});return out.map((x,i)=>({...x,title:`${String(i+1).padStart(2,'0')} · ${x.title.replace(/^\d+\.\s*/, '')}`}))},[caseData]);
 const interactionQuality=clamp(Math.round(45+(trust-50)*.35+(engagement-50)*.2+history.filter(x=>x.relevance>0).length*6+history.reduce((s,x)=>s+(x.empathy||0),0)*4-history.reduce((s,x)=>s+(x.harm||0),0)*8));
 const score=Object.values(answers).reduce((a,b)=>a+(typeof b==='number'?b:0),0); const pct=percentage(score,caseData.maxScore); const current=stages[stage];
 const record=o=>{const nt=clamp(trust+(o.trust||0)),ne=clamp(engagement+(o.engagement||0));setTrust(nt);setEngagement(ne);setEmotion(o.emotion||emotion);setRevealed(r=>[...new Set([...r,...(o.reveals||[])])]);setHistory(h=>[...h,{...o,timestamp:Date.now()}]);if(turn<sim.turns.length-1)setTurn(turn+1);else setPhase('reasoning')};
 const answer=o=>{setAnswers(a=>({...a,[current.id]:o.score}));if(stage<stages.length-1)setStage(stage+1);else setPhase('followup')};
 const finish=()=>{const result={id:caseData.id,score,maxScore:caseData.maxScore,percent:pct,confidence,duration:Math.max(1,Math.round((Date.now()-started)/1000)),interactionQuality,trust,engagement,patientEmotion:emotion,revealed,interactionHistory:history,followup:follow,completedAt:new Date().toISOString()};onComplete?.(result)};
 const started=useMemo(()=>Date.now(),[]);
 if(phase==='encounter')return <Shell m={m} onBack={onBack} caseData={caseData}><div className="sim-top"><div><span className="eyebrow">{m.label} · LIVE SIMULATION</span><h1>Meet the patient before the data.</h1><p>Listen first. Important information may emerge from the conversation rather than appearing on the first screen.</p></div><div className="sim-progress"><b>01</b><span>Patient encounter</span><i><em style={{width:`${((turn+1)/sim.turns.length)*100}%`}}/></i></div></div><div className="sim-grid"><CaseVisual module={caseData.module} patient={caseData.patient} audiogram={caseData.audiogram} title={caseData.title}/><section className="conversation-panel"><div className="patient-head"><div className="avatar">{sim.patient.avatar}</div><div><b>{sim.patient.name}</b><span>{caseData.patient?.age}-year-old {caseData.patient?.sex}</span></div><strong>● {emotion}</strong></div><div className="speech"><small>PATIENT</small><p>{sim.turns[turn].patient}</p></div><div className="prompt"><small>YOUR RESPONSE</small><h2>{sim.turns[turn].prompt}</h2></div><div className="choice-list">{sim.turns[turn].options.map(o=><button key={o.id} onClick={()=>record(o)}><span>{o.id.toUpperCase()}</span><div><b>{o.text}</b><small>{o.style}</small></div></button>)}</div><div className="meters"><div><span>Trust</span><i><em style={{width:`${trust}%`}}/></i></div><div><span>Engagement</span><i><em style={{width:`${engagement}%`}}/></i></div></div></section></div></Shell>;
 if(phase==='reasoning')return <Shell m={m} onBack={onBack} caseData={caseData}><div className="sim-top"><div><span className="eyebrow">{m.label} · CLINICAL REASONING</span><h1>Now build the clinical picture.</h1><p>The encounter is complete. Use the patient information and clinical data to make defensible decisions.</p></div><div className="sim-progress"><b>02</b><span>Clinical reasoning · {stage+1}/{stages.length}</span><i><em style={{width:`${(stage/stages.length)*100}%`}}/></i></div></div><div className="reason-grid"><aside><CaseVisual module={caseData.module} patient={caseData.patient} audiogram={caseData.audiogram}/><div className="intel"><span>INFORMATION MAP</span>{revealed.length?revealed.map(x=><p key={x}>✓ {x}</p>):<p>No additional patient disclosures recorded.</p>}</div></aside><section className="reason-panel"><div className="stage-chip">{current.title}</div><h2>{current.prompt}</h2>{current.options?.length?<div className="reason-options">{current.options.map(o=><button key={o.id} className={answers[current.id]===o.score?'selected':''} onClick={()=>answer(o)}><span>{o.id.toUpperCase()}</span><b>{o.text}</b></button>)}</div>:<button className="continue-button" onClick={()=>answer({score:0})}>Continue with extracted features →</button>}<div className="score-live"><span>Clinical reasoning</span><b>{score} / {caseData.maxScore}</b></div></section></div></Shell>;
 if(phase==='followup')return <Shell m={m} onBack={onBack} caseData={caseData}><div className="sim-top"><div><span className="eyebrow">{m.label} · FOLLOW-UP VISIT</span><h1>The patient has returned.</h1><p>Do not assume success. Reassess the patient’s stated goal, experience and outcome before closing the case.</p></div><div className="sim-progress"><b>03</b><span>Follow-up & outcome</span><i><em style={{width:'100%'}}/></i></div></div><div className="follow-grid"><CaseVisual module={caseData.module} patient={caseData.patient} audiogram={caseData.audiogram}/><section className="follow-panel"><div className="follow-patient"><div className="avatar">{sim.patient.avatar}</div><div><b>{sim.patient.name}</b><p>“I tried the plan. Some things are better, but I still have a few difficulties.”</p></div></div><h2>How will you evaluate the outcome?</h2><div className="reason-options">{[{id:'a',text:'Ask what changed, compare the result with the patient’s goal, and adapt the plan if benefit is incomplete.'},{id:'b',text:'Assume the plan worked because the patient completed it.'},{id:'c',text:'Repeat the intervention without asking about the patient’s experience.'}].map(o=><button key={o.id} className={follow===o.id?'selected':''} onClick={()=>setFollow(o.id)}><span>{o.id.toUpperCase()}</span><b>{o.text}</b></button>)}</div>{follow&&<div className="follow-feedback">{follow==='a'?'Outcome-based reassessment keeps management connected to the patient’s functional goal.':'Premature closure can miss incomplete benefit or new barriers.'}</div>}<button className="primary-button finish-button" disabled={!follow} onClick={()=>setPhase('outcome')}>Complete outcome review →</button></section></div></Shell>;
 return <Shell m={m} onBack={onBack} caseData={caseData}><section className="outcome"><div className="outcome-icon">✓</div><span className="eyebrow">CASE COMPLETE · {caseData.id}</span><h1>Clinical encounter completed.</h1><p>You navigated patient interaction, clinical reasoning, management and follow-up as one connected case.</p><div className="outcome-grid"><div><span>Clinical reasoning</span><b>{score}<small> / {caseData.maxScore}</small></b><strong>{pct}%</strong></div><div><span>Patient interaction</span><b>{interactionQuality}%</b><small>Observed communication quality</small></div><div><span>Patient state</span><b>{emotion}</b><small>Trust {trust}% · Engagement {engagement}%</small></div></div><div className="confidence"><span>How confident are you in your decisions?</span><div>{[1,2,3,4,5].map(n=><button key={n} className={confidence===n?'on':''} onClick={()=>setConfidence(n)}>{n}</button>)}</div></div><button className="primary-button" onClick={finish}>Save case & return →</button></section></Shell>;
}
function Shell({m,onBack,caseData,children}){return <main className={`final-sim ${m.tone}`}><header><button onClick={onBack} className="sim-brand"><span>A</span><b>Audio-Clinical</b> Lab</button><div><span className="module-pill">{m.label}</span><span className="case-id">{caseData.id}</span></div><button onClick={onBack} className="exit">Exit</button></header><div className="sim-body">{children}</div><footer>Educational simulation · Not for real clinical diagnosis · Prototype research data</footer></main>}
