import React, { useMemo, useState } from 'react';

const emotionMeta={calm:{icon:'🙂',label:'Calm'},concerned:{icon:'😟',label:'Concerned'},anxious:{icon:'😰',label:'Anxious'},distressed:{icon:'😣',label:'Distressed'},reassured:{icon:'😌',label:'More at ease'}};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));

export default function PatientInteraction({simulation,onComplete}){
 const [turn,setTurn]=useState(0),[trust,setTrust]=useState(simulation.initialTrust??55),[emotion,setEmotion]=useState(simulation.initialEmotion||'concerned'),[engagement,setEngagement]=useState(simulation.initialEngagement??60),[revealed,setRevealed]=useState([]),[history,setHistory]=useState([]),[repair,setRepair]=useState(false),[phase,setPhase]=useState('initial'),[finished,setFinished]=useState(false),[lastResponse,setLastResponse]=useState('');
 const prompt=simulation.turns?.[turn];
 const emotionInfo=emotionMeta[emotion]||emotionMeta.concerned;
 const interactionQuality=useMemo(()=>{const relevant=history.filter(h=>h.relevance>0).length;const empathy=history.reduce((s,h)=>s+(h.empathy||0),0);const harmful=history.reduce((s,h)=>s+(h.harm||0),0);const recovery=history.filter(h=>h.repair).length;return clamp(Math.round(42+relevant*8+empathy*5+recovery*4-harmful*9+(trust-50)*.3),0,100)},[history,trust]);
 const patientMessage=useMemo(()=>{if(phase==='followup')return trust>=65?'I have been following the plan. Some things are better, but I still have a few difficulties.':'I tried the plan, but I am still unsure whether it is helping.';if(repair)return'I feel like we moved past my concern. Could we slow down and talk about what is worrying me?';if(!prompt)return'';const v=prompt.patientByTrust;if(trust<35&&v?.low)return v.low;if(trust>=72&&v?.high)return v.high;if(trust<35)return'I am not really sure what else to say. I am still worried.';if(trust>=72)return`${prompt.patient} I feel comfortable telling you more.`;return prompt.patient},[prompt,trust,repair,phase]);
 const record=(option,isRepair=false)=>{const nextTrust=clamp(trust+(option.trust||0),0,100),nextEng=clamp(engagement+(option.engagement||0),0,100),nextEmotion=option.emotion||emotion,nextRev=[...new Set([...revealed,...(option.reveals||[])])],event={id:option.id,relevance:option.relevance||0,empathy:option.empathy||0,harm:option.harm||0,repair:isRepair,timestamp:Date.now(),phase};const nextHistory=[...history,event];setTrust(nextTrust);setEngagement(nextEng);setEmotion(nextEmotion);setRevealed(nextRev);setHistory(nextHistory);setLastResponse(option.response||'The patient responds to your approach.');if(isRepair){setRepair(false);return}if(phase==='followup'){setFinished(true);onComplete?.({interactionQuality:clamp(Math.round(42+nextHistory.filter(h=>h.relevance>0).length*8+nextHistory.reduce((s,h)=>s+(h.empathy||0),0)*5+nextHistory.filter(h=>h.repair).length*4-nextHistory.reduce((s,h)=>s+(h.harm||0),0)*9+(nextTrust-50)*.3),0,100),trust:nextTrust,engagement:nextEng,emotion:nextEmotion,revealed:nextRev,history:nextHistory,followupCompleted:true});return}if(option.harm&&nextTrust<55){setRepair(true);return}if(turn<(simulation.turns?.length||1)-1)setTurn(turn+1);else setPhase('followup')};
 if(finished)return <section className="patient-interaction complete"><div className="interaction-complete-icon">✓</div><div><p className="eyebrow">CLINICAL ENCOUNTER COMPLETE</p><h2>Assessment → management → follow-up completed.</h2><p className="interaction-note">The patient returned after the initial plan. Your final outcome includes communication, disclosure, recovery and reassessment behaviour.</p><div className="interaction-summary-grid"><div><span>Observed state</span><b>{emotionInfo.icon} {emotionInfo.label}</b></div><div><span>Trust</span><b>{trust}%</b></div><div><span>Engagement</span><b>{engagement}%</b></div><div><span>Interaction quality</span><b>{interactionQuality}%</b></div></div><div className="revealed-facts">{revealed.map(f=><span key={f}>✓ {f}</span>)}</div><button className="primary-button" type="button" onClick={()=>onComplete?.({interactionQuality,trust,engagement,emotion,revealed,history,followupCompleted:true},true)}>Continue to clinical reasoning →</button></div></section>;
 const options=phase==='followup'?[{id:'f1',text:'Ask what changed, compare the result with the patient’s stated goal, and adapt the plan if benefit is incomplete.',style:'Outcome-based reassessment',trust:10,engagement:10,relevance:2,empathy:2,emotion:'reassured',response:'That makes sense. I feel like we are checking whether the plan actually works for me.'},{id:'f2',text:'Assume the intervention worked because the patient completed the plan.',style:'Premature closure',trust:-6,engagement:-8,harm:1,emotion:'concerned',response:'I still have problems, but I suppose we can leave it there.'},{id:'f3',text:'Repeat the same intervention without asking about the patient’s experience.',style:'Plan without reassessment',trust:-9,engagement:-10,harm:1,emotion:'anxious',response:'I was hoping you would ask what has actually changed.'}]:repair?[{id:'r1',text:'Acknowledge the concern, slow down, and invite the patient to continue.',style:'Communication repair',trust:12,engagement:10,empathy:3,emotion:'reassured',response:'Thank you. I feel more comfortable explaining it now.'},{id:'r2',text:'Continue the assessment without revisiting the concern.',style:'Missed repair opportunity',trust:-8,engagement:-10,harm:1,emotion:'distressed',response:'Okay... I will just wait for the test.'},{id:'r3',text:'Tell the patient to stop worrying until the results are available.',style:'Dismissive reassurance',trust:-10,engagement:-12,harm:1,emotion:'anxious',response:'That makes me feel even less understood.'}]:prompt?.options||[];
 return <section className="patient-interaction"><div className="patient-scene"><div className="patient-avatar-large">{simulation.patient?.avatar||'P'}</div><div className="patient-scene-copy"><span className="card-kicker">SIMULATED PATIENT · {phase==='followup'?'FOLLOW-UP VISIT':'LIVE ENCOUNTER'}</span><h2>{simulation.patient?.name||'Patient'}</h2><p>{phase==='followup'?'The patient has returned to report what happened after the agreed plan.':simulation.patient?.intro||'The patient is waiting for you to begin the consultation.'}</p></div><div className={`patient-state ${emotion}`}><span>{emotionInfo.icon}</span><div><small>OBSERVED STATE</small><b>{emotionInfo.label}</b></div></div></div><div className="conversation-card"><div className="conversation-header"><span>{phase==='followup'?'FOLLOW-UP · OUTCOME REVIEW':repair?'COMMUNICATION REPAIR':`ENCOUNTER · TURN ${turn+1}/${simulation.turns.length}`}</span><span>Patient behaviour is state-dependent</span></div><div className="patient-speech"><span className="speech-avatar">{simulation.patient?.avatar||'P'}</span><div><b>{simulation.patient?.name||'Patient'}</b><p>{patientMessage}</p></div></div>{lastResponse&&<div className="patient-reaction"><span>Patient response</span><b>{lastResponse}</b></div>}<div className="clinician-prompt"><span>{phase==='followup'?'OUTCOME & REASSESSMENT':repair?'REPAIR THE ENCOUNTER':'YOUR RESPONSE'}</span><h3>{phase==='followup'?'The patient reports a partial or uncertain outcome. What will you do next?':repair?'The conversation has become strained. What will you do now?':prompt?.prompt}</h3></div><div className="interaction-options">{options.map(o=><button key={o.id} type="button" className="interaction-option" onClick={()=>record(o,repair)}><span className="option-marker">{o.id.toUpperCase()}</span><span><b>{o.text}</b><small>{o.style}</small></span></button>)}</div></div><div className="interaction-meter-row"><div><span>Observed trust trajectory</span><div className="interaction-meter"><i style={{width:`${trust}%`}}/></div></div><div><span>Engagement</span><div className="interaction-meter"><i style={{width:`${engagement}%`}}/></div></div><p>Analytics are recorded for the prototype; interpret the patient through words, behaviour and disclosed information.</p></div></section>;
}
