const state={stream:null,recorder:null,chunks:[],started:0,raf:null,samples:[],events:[],sessionId:null,duration:0,rate:0,metrics:null};
const $=s=>document.querySelector(s), root=$('#app');
root.innerHTML=`<div class="shell"><header class="top"><div class="brand"><span>DDK</span>Lab</div><div class="badge">LOCAL ONLY · DSP PRELIMINARY</div></header><div class="grid"><section class="panel"><h2>New session</h2><div class="controls"><div class="field"><label>Participant code</label><input id="pid" value="DDK-001"></div><div class="field"><label>Age / clinical mode</label><select id="age"><option>Child</option><option selected>Adult</option><option>Geriatric</option><option>Dysarthria</option></select></div><div class="field"><label>Task</label><select id="task"><option value="AMR">AMR</option><option value="SMR">SMR</option></select></div><div class="field"><label>Target</label><select id="target"><option>PA</option><option>TA</option><option>KA</option></select></div></div><div class="target" id="targetText">PA</div><div class="timer" id="timer">15.0</div><div class="recording"><button class="btn primary" id="start">START 15 s</button><button class="btn danger" id="stop" disabled>STOP & ANALYZE</button></div><div class="child" id="child" hidden><div id="car" class="car">🚗</div><div>Reinforcement: each detected production/cycle advances the car.</div></div><p class="notice">One continuous 15-second take. No pause or replay. Audio stays on this device.</p><div class="qc" id="qc">Recording QC: waiting</div></section><section class="panel"><h2>Waveform</h2><div class="wave"><canvas id="wave" width="900" height="310"></canvas></div><div class="result"><div class="metric"><strong id="auto">—</strong><small>Automatic count</small></div><div class="metric"><strong id="verified">REVIEW</strong><small>Verified count</small></div><div class="metric"><strong id="rate">—</strong><small>Rate / sec</small></div><div class="metric"><strong id="dur">—</strong><small>Duration</small></div></div><div class="status" id="status">Ready. Select task and start the 15-second recording.</div><div class="events" id="events"></div><div class="analysis" id="analysis"></div><div class="validation"><h3>Research validation</h3><label>Known / clinician count <input id="truth" type="number" min="0" step="1" placeholder="optional"></label><button class="btn" id="validate">Compare</button><div id="validationResult">Enter a ground-truth count after analysis to calculate error.</div></div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn" id="exportJson" disabled>Export JSON</button><button class="btn" id="exportCsv" disabled>Export CSV</button></div></section></div><div class="footer">DDKLab · deterministic local DSP · research validation required before diagnostic interpretation.</div></div>`;
const canvas=$('#wave'),ctx=canvas.getContext('2d');
function taskUI(){const smr=$('#task').value==='SMR';$('#target').innerHTML=smr?'<option>PA-TA-KA</option>':'<option>PA</option><option>TA</option><option>KA</option>';$('#targetText').textContent=smr?'PA-TA-KA':$('#target').value;$('#child').hidden=$('#age').value!=='Child';}
$('#task').onchange=taskUI;$('#target').onchange=()=>{$('#targetText').textContent=$('#task').value==='SMR'?'PA-TA-KA':$('#target').value};$('#age').onchange=taskUI;
function draw(data=null){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#080d18';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#1e293b';ctx.beginPath();ctx.moveTo(0,155);ctx.lineTo(canvas.width,155);ctx.stroke();if(!data||!data.length)return;ctx.strokeStyle='#7dd3fc';ctx.lineWidth=1.25;ctx.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*canvas.width;const y=155-data[i]*135;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();state.events.forEach((e,i)=>{const x=e.t/state.duration*canvas.width;ctx.strokeStyle=e.confidence<0.55?'#fb7185':'#fbbf24';ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,295);ctx.stroke();ctx.fillStyle=e.confidence<0.55?'#fb7185':'#fbbf24';ctx.font='12px sans-serif';ctx.fillText(String(i+1),Math.min(canvas.width-20,x+3),28)});}
function rmsEnvelope(samples,rate,frameMs=10){const win=Math.max(16,Math.round(rate*frameMs/1000)),out=[];for(let i=0;i<samples.length;i+=win){let s=0;const end=Math.min(samples.length,i+win);for(let j=i;j<end;j++)s+=samples[j]*samples[j];out.push(Math.sqrt(s/Math.max(1,end-i)))}return out;}
function movingAverage(a,r){if(!a.length)return[];const out=new Array(a.length);for(let i=0;i<a.length;i++){let s=0,n=0;for(let j=Math.max(0,i-r);j<=Math.min(a.length-1,i+r);j++){s+=a[j];n++;}out[i]=s/n;}return out;}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2;}
function quantile(a,q){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);return b[Math.max(0,Math.min(b.length-1,Math.floor((b.length-1)*q)))];}
function localMin(a,l,r){l=Math.max(0,l);r=Math.min(a.length-1,r);let m=Infinity;for(let i=l;i<=r;i++)m=Math.min(m,a[i]);return Number.isFinite(m)?m:0;}
function detect(samples,rate){
  const env=rmsEnvelope(samples,rate,10);if(env.length<5)return[];
  const smooth=movingAverage(env,2);const base=quantile(smooth,.20),q50=quantile(smooth,.50),q90=quantile(smooth,.90);const scale=Math.max(q90-base,1e-9);const n=smooth.map(v=>Math.max(0,(v-base)/scale));
  const dys=$('#age').value==='Dysarthria';
  // One production should produce one dominant envelope maximum. The detector therefore
  // searches for maxima with local prominence rather than counting every threshold crossing.
  // The minimum distance is deliberately below normal DDK syllable intervals so rapid DDK
  // is preserved, while smaller within-syllable ripples are suppressed by prominence.
  const minGap=dys?.075:.080;
  const halfWindow=.065;
  const promFloor=dys?.035:.045;
  const heightFloor=dys?.085:.070;
  const peaks=[];
  for(let i=2;i<n.length-2;i++){
    const v=n[i];if(v<heightFloor||v<n[i-1]||v<n[i+1])continue;
    const w=Math.max(2,Math.round(halfWindow/.010));
    const left=localMin(n,i-w,i-1),right=localMin(n,i+1,i+w);const prominence=v-Math.max(left,right);
    if(prominence<promFloor)continue;
    // onset support helps reject isolated electrical/microphone spikes.
    const onset=v-localMin(n,Math.max(0,i-Math.round(.045/.010)),i);
    if(onset<Math.max(.012,promFloor*.45))continue;
    peaks.push({i,t:i*.010,a:v,prominence,onset,score:.62*v+.28*prominence+.10*Math.min(1,onset/.10)});
  }
  peaks.sort((a,b)=>b.score-a.score);
  const selected=[];const gap=Math.max(1,Math.round(minGap/.010));
  for(const p of peaks){
    const near=selected.findIndex(x=>Math.abs(x.i-p.i)<gap);
    if(near<0)selected.push(p);else if(p.score>selected[near].score)selected[near]=p;
  }
  selected.sort((a,b)=>a.i-b.i);
  // Remove edge artefacts and very-low isolated events, but do not use a high global
  // amplitude threshold: weak real productions must remain candidates for human review.
  const dur=samples.length/rate;
  const out=selected.filter(p=>p.t>.12&&p.t<dur-.08).map(p=>({t:p.t,a:p.a,confidence:Math.min(1,Math.max(.05,.55*p.a+.35*Math.min(1,p.prominence/.25)+.10*Math.min(1,p.onset/.10)))}));
  return out;
}
function intervalMetrics(events){if(events.length<2)return{meanInterval:null,sdInterval:null,cv:null};const x=events.slice(1).map((e,i)=>e.t-events[i].t),mean=x.reduce((a,b)=>a+b,0)/x.length,sd=Math.sqrt(x.reduce((a,b)=>a+(b-mean)**2,0)/Math.max(1,x.length-1));return{meanInterval:mean,sdInterval:sd,cv:mean?sd/mean*100:null};}
function reference(){const mode=$('#age').value,target=$('#target').value;if(mode!=='Adult')return{label:'No universal reference loaded for this mode',note:'Use an age/task/diagnosis-appropriate validated reference; DDKLab will not invent a cutoff.'};const m={PA:6.4,TA:6.1,KA:5.7}[target]||null;return m?{label:`Published adult mean: ${m.toFixed(1)} syllables/s`,note:'Portnoy & Aronson (1982), n=30 normal adults; this is a reference mean, not a diagnostic cutoff.'}:{label:'Published adult reference not mapped',note:'Select PA, TA or KA.'};}
function setStatus(t){$('#status').textContent=t}
function renderEvents(){const box=$('#events');box.innerHTML=state.events.map((e,i)=>`<div class="event"><span>Event ${i+1} · ${e.t.toFixed(3)} s</span><span>${Math.round(e.confidence*100)}% · AUTO</span></div>`).join('');}
function finish(samples,rate,duration){state.duration=duration;state.samples=samples;state.events=detect(samples,rate);const smr=$('#task').value==='SMR',syllables=state.events.length,count=smr?Math.floor(syllables/3):syllables,rem=smr?syllables%3:0;state.rate=count/Math.max(duration,.001);const im=intervalMetrics(state.events);state.metrics={syllables,count,smrRemainder:rem,...im};const rms=Math.sqrt(samples.reduce((s,v)=>s+v*v,0)/Math.max(1,samples.length)),peak=Math.max(...samples.map(v=>Math.abs(v)));const clipped=samples.some(v=>Math.abs(v)>=.99),quality=rms<.003?'TOO QUIET':clipped?'CLIPPING DETECTED':state.events.length===0?'NO EVENTS':'PASS';$('#qc').textContent=`Recording QC: ${quality} · RMS ${rms.toFixed(4)} · peak ${peak.toFixed(3)}`;$('#auto').textContent=count;$('#verified').textContent='REVIEW';$('#rate').textContent=state.rate.toFixed(2);$('#dur').textContent=duration.toFixed(2)+' s';const ref=reference();$('#analysis').innerHTML=`<div><b>Event count:</b> ${syllables}${smr?` syllable events → ${count} complete PA-TA-KA cycles${rem?' + '+rem+' extra event(s) — REVIEW':''}`:''}</div><div><b>Mean interval:</b> ${im.meanInterval==null?'—':(im.meanInterval*1000).toFixed(1)+' ms'} · <b>SD:</b> ${im.sdInterval==null?'—':(im.sdInterval*1000).toFixed(1)+' ms'} · <b>CV:</b> ${im.cv==null?'—':im.cv.toFixed(1)+'%'}</div><div><b>Reference:</b> ${ref.label}</div><small>${ref.note}</small>`;setStatus(quality==='PASS'?`PRELIMINARY result · ${count} ${smr?'SMR cycles':'AMR productions'} detected. Verify every marker.`:`REVIEW REQUIRED · ${quality}`);renderEvents();const stride=Math.max(1,Math.floor(samples.length/900));draw(samples.filter((_,i)=>i%stride===0));$('#exportJson').disabled=false;$('#exportCsv').disabled=false;saveSession(rate,count,quality);}
async function saveSession(rate,count,quality){state.sessionId=`DDK-${Date.now()}`;const data={id:state.sessionId,participant:$('#pid').value,ageMode:$('#age').value,task:$('#task').value,target:$('#targetText').textContent,duration:state.duration,automaticCount:count,verifiedCount:null,rate,events:state.events,metrics:state.metrics,quality,reference:reference(),detector:'DDKLab-DSP-v19',protocol:'15-second-fixed',status:'REVIEW',createdAt:new Date().toISOString(),sampleRate:null};try{await window.ddklab.storage.saveSession(data)}catch(e){console.error(e);setStatus('Analysis complete, but local session storage failed.');}}
async function start(){try{state.stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.recorder=new MediaRecorder(state.stream);state.chunks=[];state.samples=[];state.events=[];state.started=performance.now();state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=async()=>{try{const blob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'}),audio=new AudioContext(),buf=await audio.decodeAudioData(await blob.arrayBuffer()),samples=buf.getChannelData(0);finish(samples,buf.sampleRate,Math.min(15,(performance.now()-state.started)/1000));await audio.close();}catch(e){console.error(e);setStatus('Audio processing failed. The recording was not scored.');}finally{state.stream?.getTracks().forEach(t=>t.stop());}};state.recorder.start();$('#start').disabled=true;$('#stop').disabled=false;setStatus('RECORDING… 15-second protocol active.');tick();setTimeout(()=>{if(state.recorder&&state.recorder.state==='recording')stop();},15000);}catch(e){setStatus('Microphone unavailable: '+e.message);}}
function tick(){if(!state.recorder||state.recorder.state!=='recording')return;const left=Math.max(0,15-(performance.now()-state.started)/1000);$('#timer').textContent=left.toFixed(1);state.raf=requestAnimationFrame(tick);}
function stop(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();$('#start').disabled=false;$('#stop').disabled=true;setStatus('Processing waveform…');cancelAnimationFrame(state.raf)}}
$('#start').onclick=start;$('#stop').onclick=stop;
$('#validate').onclick=()=>{const truth=Number($('#truth').value),auto=Number($('#auto').textContent);if(!Number.isFinite(truth)||truth<0||!Number.isFinite(auto))return;const err=auto-truth,abs=Math.abs(err),pct=truth?abs/truth*100:0;$('#validationResult').innerHTML=`<b>Automatic:</b> ${auto} · <b>Ground truth:</b> ${truth} · <b>Error:</b> ${err>0?'+':''}${err} · <b>Absolute error:</b> ${abs} · <b>Percentage error:</b> ${pct.toFixed(1)}%`;state.metrics={...state.metrics,groundTruth:truth,error:err,absoluteError:abs,percentageError:pct};};
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#exportJson').onclick=()=>download(`${state.sessionId||'DDK-session'}.json`,JSON.stringify({id:state.sessionId,participant:$('#pid').value,ageMode:$('#age').value,task:$('#task').value,target:$('#targetText').textContent,duration:state.duration,automaticCount:$('#auto').textContent,verifiedCount:null,rate:state.rate,events:state.events,metrics:state.metrics,reference:reference(),detector:'DDKLab-DSP-v19',protocol:'15-second-fixed'},null,2),'application/json');
$('#exportCsv').onclick=()=>download(`${state.sessionId||'DDK-session'}.csv`,'event_id,timestamp,confidence,source\n'+state.events.map((e,i)=>`${i+1},${e.t.toFixed(4)},${e.confidence.toFixed(3)},automatic`).join('\n'),'text/csv');
taskUI();draw();