const state={stream:null,recorder:null,chunks:[],started:0,raf:null,analyser:null,buffer:null,samples:[],events:[],sessionId:null,car:0};
const $=s=>document.querySelector(s);
const root=$('#app');
root.innerHTML=`<div class="shell"><header class="top"><div class="brand"><span>DDK</span>Lab</div><div class="badge">LOCAL ONLY · PRELIMINARY DSP</div></header><div class="grid"><section class="panel"><h2>New session</h2><div class="controls"><div class="field"><label>Participant code</label><input id="pid" value="DDK-001"></div><div class="field"><label>Age mode</label><select id="age"><option>Child</option><option selected>Adult</option><option>Geriatric</option></select></div><div class="field"><label>Task</label><select id="task"><option value="AMR">AMR</option><option value="SMR">SMR</option></select></div><div class="field"><label>Target</label><select id="target"><option>PA</option><option>TA</option><option>KA</option></select></div></div><div class="target" id="targetText">PA</div><div class="timer" id="timer">00:00.0</div><div class="recording"><button class="btn primary" id="start">START</button><button class="btn danger" id="stop" disabled>STOP</button></div><div class="child" id="child" hidden><div id="car" class="car">🚗</div><div>Reinforcement: each detected production/cycle advances the car.</div></div><p class="notice">One continuous take. No pause, replay, or manual save. Audio stays on this device.</p></section><section class="panel"><h2>Waveform</h2><div class="wave"><canvas id="wave" width="900" height="310"></canvas></div><div class="result"><div class="metric"><strong id="auto">—</strong><small>Automatic count</small></div><div class="metric"><strong id="verified">—</strong><small>Verified count</small></div><div class="metric"><strong id="rate">—</strong><small>Rate / sec</small></div><div class="metric"><strong id="dur">—</strong><small>Duration</small></div></div><div class="status" id="status">Ready. Select a task and start one continuous recording.</div><div class="events" id="events"></div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn" id="exportJson" disabled>Export JSON</button><button class="btn" id="exportCsv" disabled>Export CSV</button></div></section></div><div class="footer">DDKLab 0.1 · Automatic detector is PRELIMINARY and requires human verification before research use.</div></div>`;

const canvas=$('#wave'),ctx=canvas.getContext('2d');
function taskUI(){const smr=$('#task').value==='SMR';$('#target').innerHTML=smr?'<option>PA-TA-KA</option>':'<option>PA</option><option>TA</option><option>KA</option>';$('#targetText').textContent=smr?'PA-TA-KA':$('#target').value;$('#child').hidden=$('#age').value!=='Child';}
$('#task').onchange=taskUI;$('#target').onchange=()=>{$('#targetText').textContent=$('#task').value==='SMR'?'PA-TA-KA':$('#target').value};$('#age').onchange=taskUI;
function draw(data=null){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#080d18';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#1e293b';ctx.beginPath();ctx.moveTo(0,155);ctx.lineTo(canvas.width,155);ctx.stroke();if(!data||!data.length)return;ctx.strokeStyle='#7dd3fc';ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<data.length;i++){const x=i/(data.length-1)*canvas.width;const y=155-data[i]*135;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();state.events.forEach((e,i)=>{const x=e.t/state.duration*canvas.width;ctx.strokeStyle='#fbbf24';ctx.beginPath();ctx.moveTo(x,15);ctx.lineTo(x,295);ctx.stroke();ctx.fillStyle='#fbbf24';ctx.fillText(String(i+1),x+3,28)});}
function envelope(samples,rate){const win=Math.max(16,Math.floor(rate*.012));const out=[];for(let i=0;i<samples.length;i+=win){let s=0;const end=Math.min(samples.length,i+win);for(let j=i;j<end;j++)s+=samples[j]*samples[j];out.push(Math.sqrt(s/(end-i)))}return out}
function detect(samples,rate){const env=envelope(samples,rate);if(!env.length)return[];const max=Math.max(...env)||1;const norm=env.map(v=>v/max);const smooth=norm.map((v,i)=>{let s=0,n=0;for(let j=Math.max(0,i-2);j<=Math.min(norm.length-1,i+2);j++){s+=norm[j];n++}return s/n});const floor=Math.max(.025,quantile(smooth,.2)*1.8);const candidates=[];for(let i=1;i<smooth.length-1;i++){if(smooth[i]>floor&&smooth[i]>=smooth[i-1]&&smooth[i]>=smooth[i+1])candidates.push({i,a:smooth[i]})}const minGap=Math.max(2,Math.round(rate*.11/(Math.max(1,Math.floor(rate*.012)))));const chosen=[];for(const c of candidates){const last=chosen[chosen.length-1];if(!last||c.i-last.i>=minGap)chosen.push(c);else if(c.a>last.a)chosen[chosen.length-1]=c}const step=Math.max(1,Math.floor(rate*.012));return chosen.map(c=>({t:c.i*step/rate,a:c.a,confidence:Math.min(1,Math.max(.1,(c.a-floor)/(1-floor)))}));}
function quantile(a,q){const b=[...a].sort((x,y)=>x-y);return b[Math.floor((b.length-1)*q)]||0}
function setStatus(t){$('#status').textContent=t}
function renderEvents(){const box=$('#events');box.innerHTML=state.events.map((e,i)=>`<div class="event"><span>Event ${i+1} · ${(e.t).toFixed(3)} s</span><span>${Math.round(e.confidence*100)}% · AUTO</span></div>`).join('');}
function finish(samples,rate,duration){state.duration=duration;state.events=detect(samples,rate);const isSmr=$('#task').value==='SMR';const count=isSmr?Math.floor(state.events.length/3):state.events.length;$('#auto').textContent=count;$('#verified').textContent=count;$('#rate').textContent=(count/Math.max(duration,.001)).toFixed(2);$('#dur').textContent=duration.toFixed(2)+' s';setStatus(`PRELIMINARY result · ${count} ${isSmr?'SMR cycles':'AMR productions'} detected. Inspect waveform before research use.`);renderEvents();draw(samples.filter((_,i)=>i%Math.max(1,Math.floor(samples.length/900))===0));$('#exportJson').disabled=false;$('#exportCsv').disabled=false;state.car=count;$('#car').style.transform=`translateX(${Math.min(260,count*32)}px)`;saveSession(rate,count);}
async function saveSession(rate,count){state.sessionId=`DDK-${Date.now()}`;const data={id:state.sessionId,participant:$('#pid').value,ageMode:$('#age').value,task:$('#task').value,target:$('#targetText').textContent,duration:state.duration,automaticCount:count,verifiedCount:count,rate:count/Math.max(state.duration,.001),events:state.events,detector:'PRELIMINARY-ENV-1',status:'REVIEW',createdAt:new Date().toISOString(),sampleRate:rate};try{await window.ddklab.storage.saveSession(data)}catch(e){console.error(e);setStatus('Analysis complete, but local session storage failed.');}}
async function start(){try{state.stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.recorder=new MediaRecorder(state.stream);state.chunks=[];state.samples=[];state.started=performance.now();state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=async()=>{const blob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});const audio=new AudioContext();const buf=await audio.decodeAudioData(await blob.arrayBuffer());const samples=buf.getChannelData(0);finish(samples,buf.sampleRate,(performance.now()-state.started)/1000);state.stream.getTracks().forEach(t=>t.stop());};state.recorder.start();$('#start').disabled=true;$('#stop').disabled=false;setStatus('RECORDING… produce the target continuously.');tick();}catch(e){setStatus('Microphone unavailable: '+e.message)}}
function tick(){if(!state.recorder||state.recorder.state!=='recording')return;$('#timer').textContent=((performance.now()-state.started)/1000).toFixed(1)+' s';state.raf=requestAnimationFrame(tick)}
function stop(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();$('#start').disabled=false;$('#stop').disabled=true;setStatus('Processing waveform…');cancelAnimationFrame(state.raf)}}
$('#start').onclick=start;$('#stop').onclick=stop;
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#exportJson').onclick=()=>download(`${state.sessionId||'DDK-session'}.json`,JSON.stringify({id:state.sessionId,participant:$('#pid').value,task:$('#task').value,target:$('#targetText').textContent,duration:state.duration,automaticCount:state.events.length,events:state.events},null,2),'application/json');
$('#exportCsv').onclick=()=>download(`${state.sessionId||'DDK-session'}.csv`,'event_id,timestamp,confidence,source\n'+state.events.map((e,i)=>`${i+1},${e.t.toFixed(4)},${e.confidence.toFixed(3)},automatic`).join('\n'),'text/csv');
taskUI();draw();
